name = "ao-challenger"
main = "main.js"
compatibility_date = "2023-01-01"

[[triggers]]
crons = ["* * * * *"]  # For periodic tasks if needed

[vars]
DISCORD_TOKEN = ""
MONGO_URI = ""
DISCORD_PUBLIC_KEY = ""

[[routes]]
pattern = "your-domain.com/interactions"
zone_name = "your-domain.com"